Feature/various improvements
olivierperez/ReleaseScript pull request #3
Opened 2020-08-30 16:44 UTC by d-fournier

I made several improvements:
- Split the `Render` and `Formatter`
    - The `Formatter` will convert the change to a high level format
    - The `Render` will render in its own format
- Add module for command line format
- Manage case without given version

2020-09-06 17:31 UTC, olivierperez requested changes

2020-09-06 17:31 UTC, olivierperez commented on command_line/build.gradle
> +    id 'org.jetbrains.kotlin.jvm' version '1.4.0'
La session de Kotlin pourrait être définie au top level, et ici ne garder que `id 'org.jetbrains.kotlin.jvm'`

2020-09-06 17:31 UTC, olivierperez commented on command_line/src/main/kotlin/fr/o80/release/Arguments.kt
> +    val folder by parser.storing(
Ce serait bien d'avoir le type de chaque paramètres ici de façon explicite

2020-09-06 17:31 UTC, olivierperez commented on command_line/src/main/kotlin/fr/o80/release/Arguments.kt
> +        "-f", "--folder",
Qu'est-ce que vous pensez de "directory" plutôt ? -f me fait beaucoup penser à --force qui est souvent utilisé sur les CLI

2020-09-06 17:31 UTC, olivierperez commented on command_line/src/main/kotlin/fr/o80/release/Main.kt
> +    val workingDirectory = File(System.getProperty("user.dir"), parsedArgs.folder)
user.dir ? Ça correspond pas au Home de l'utilisateur ? Pourquoi pas juste `File(parsedArgs.folder)` ?

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/ChangelogGenerator.kt
> +        val allVersionsFolder = getVersionsFolder(workingDirectory, versions)
getVersionFolders() non ? Je mettrai plutôt le S à Folders

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/ChangelogGenerator.kt
> +        val allVersionsFolder = getVersionsFolder(workingDirectory, versions)
Et renommer la variable versionFolders

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/ChangelogGenerator.kt
> +            .takeIf { it.exists() }
On ignore si un dossier de version n'existe pas ?

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/parser/md/MarkdownParser.kt
> +    private val configuration: ChangelogConfiguration
Ce paramètre n'est pas utilisé

2020-09-06 17:31 UTC, olivierperez commented on command_line/build.gradle
> +    implementation("com.xenomachina:kotlin-argparser:2.0.7")
```suggestion
    implementation "com.xenomachina:kotlin-argparser:2.0.7"
```

2020-09-06 17:31 UTC, olivierperez commented on command_line/src/main/kotlin/fr/o80/release/Arguments.kt
> +    val folder by parser.storing(
Et qu'est-ce que vous pensez d'expliciter de quel "folder" il s'agit ? Genre `val versionFolder: String` ?

2020-09-06 17:31 UTC, olivierperez commented on command_line/src/main/kotlin/fr/o80/release/Arguments.kt
> +    val ignoreSlug by parser.flagging(
"slug" ne me parle pas vraiment, et "ignore" me faisait plutôt à un algorithme qui ne prend pas en compte une information alors qu'ici c'est dans le but de ne pas afficher une information.

Est-ce qu'on pourrait partir sur "dontRenderIds" ?

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/ChangelogGenerator.kt
> +        val formatter: Formatter = TextFormatter(renderer, configuration)
```suggestion
		// TODO Passer toutes les dépendances via le constructeur (de même pour Converter plus bas)
        val markdownParser: Parser = MarkdownParser(configuration)
        val renderer = MarkdownRenderer(configuration)
        val formatter: Formatter = TextFormatter(renderer, configuration)
```

2020-09-06 17:31 UTC, olivierperez commented on library/build.gradle
> +}
On peut bouger tout ça dans `allprojects {` non ?

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/ChangelogConfiguration.kt
> +private val VALID_TYPES = listOf("feature", "fix")
❓ Est-ce que, pour plus tard, ça serait pas une bonne idée d'avoir un fichier de conf.

- dans le fichier de conf, on met ce qui est relatif au projet
- dans les arguments du programmes, on met ce qui est relatif au moment où on génère le changelog

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/formatter/TextFormatter.kt
> +    private val configuration: ChangelogConfiguration
Le TextFormatter devrait attendre un paramètre le "ignoreSlug" directement plutôt que de la Conf qui me semble un peu fourre-tout.

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/formatter/TextFormatter.kt
> +    override fun process(versionName: String, changesByType: Map<String, List<Change>>) {
Je suis pas fan :
- d'un "Formatter" qui a une méthode "process" et pas de méthode "format"
- de la méthode principale d'un "Formatter" qui ne retourne rien, il y a donc un effet de bord
- que l'effet de bord soit envoyé d'un Formatter à un Renderer

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/formatter/TextFormatter.kt
> +    private val rendererProvider: TextRenderer,
Variable mal nommée

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/formatter/TextFormatter.kt
> +    private var hasContent = false
Variable inutilisée

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/formatter/TextFormatter.kt
> +class TextFormatter(
Cette classe me semble overkill, elle fait beaucoup de choses mais très peu relatives à un formatting.

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/formatter/TextFormatter.kt
> +    }
Pour gérer le cas du "ingore", on pourrait imaginer un pattern Stratégie avec une interface `ChangeFormatter` et 2 implémentations `SimpleChangeFormatter` et `ComplexChangeFormatter`.

2020-09-06 17:31 UTC, olivierperez commented on library/src/test/kotlin/fr/o80/release/Helpers.kt
> +    )
Cette variable "Configuration" conditionne beaucoup de chose dans le code, je suis pas fan de l'avoir en dur dans un Helper.
C'est plutôt le genre de truc que je mettrai dans la partie "//Given" d'un test, ou dans un `@BeforeEach`

2020-09-06 17:31 UTC, olivierperez commented on library/src/test/kotlin/fr/o80/release/MainKtTest.kt
> +val expectedOutputV2 = """|# Changelog
Saut de ligne ?
```suggestion
                          |""".trimMargin().replace("\n", System.lineSeparator())

val expectedOutputV2 = """|# Changelog
```

2020-09-06 17:31 UTC, olivierperez commented on library/src/test/kotlin/fr/o80/release/MainKtTest.kt
> +internal class MainKtTest {
Le classe devrait être nommée `ChangelogGeneratorTest`

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/Converter.kt
> +class Converter(
Cette classe converti quoi ? Ça devrait apparaitre dans le nom de la classe.

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/Converter.kt
> +    fun convert(parsedFiles: List<ParsedFile>): SortedMap<String, List<Change>> {
Cette méthode fait beaucoup de choses dont il faut avoir conscience quand on travaille dans la classe `ChangelogGenerator`. Il fautdrait voir pour découper les responsabilités.

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/Converter.kt
> +    fun convert(parsedFiles: List<ParsedFile>): SortedMap<String, List<Change>> {
D'ailleurs on voit bien qu'avec cette architecture, la méthode `toChange` devient privée et par conséquent non testable unitairement.

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/Converter.kt
> +    private val configuration: ChangelogConfiguration
Un `Converter` n'a pas besoin de `ChangelogConfiguration` pour fonctionner, mais plutôt d'une liste de types valides.

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/Converter.kt
> +open class ConversionException(message: String? = null, cause: Throwable? = null) : Exception(message, cause)
Ce niveau d'abstraction pourrait être ignoré en Kotlin puisqu'on ne déclare pas les Exception renvoyées.

_D'ailleurs est-ce que ça vous interesserait qu'on code de façon à ne jamais déclencher d'Exceptions ?_

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/parser/md/MarkdownReader.kt
> +    private val streamReader = inputStream.bufferedReader()
Cette variable pourrait bien être inlinée.

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/parser/md/MarkdownReader.kt
> +private const val HEADERS_SEPARATOR = "---"
Vous êtes partisants de mettre les constantes en fin de fichiers ?

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/parser/md/MarkdownReader.kt
> +            .toList()
On est déjà sur une `List`

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/utils/IteratorHelpers.kt
> +fun <T> Iterator<T>.firstOrNull(): T? = if (hasNext()) next() else null
On devrait la nommer `nextOrNull` non ?

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/parser/md/MarkdownReader.kt
> +            ?: ""
Ici j'aurai bien vu un `fold` avec un `StringBuilder` :

```kotlin
fun readRemaining(): String {
    return fileIterator
        .fold({StringBuilder(it)}) { accumulator: StringBuilder, line: String ->
            accumulator.append("\n" + line)
        }
        ?.toString()
        ?: ""
}
```

et 

```kotlin
fun <A, E> Iterator<E>.fold(initWith: (E) -> A, reducer: (A, E) -> A): A? {
    var accumulator: A? = null
    while (hasNext()) {
        val curAcc = accumulator
        accumulator = if (curAcc == null) {
            initWith(next())
        } else {
            reducer(curAcc, next())
        }
    }
    return accumulator
}
```

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/render/md/MarkdownRenderer.kt
> +    private val configuration: ChangelogConfiguration
Variable inutilisée

2020-09-06 17:31 UTC, olivierperez commented on library/src/main/kotlin/fr/o80/release/render/Renderer.kt
> +}
Ce niveau d'abstraction apporte quelque chose ?

2020-09-07 19:01 UTC, d-fournier commented on command_line/src/main/kotlin/fr/o80/release/Main.kt
> +    val workingDirectory = File(System.getProperty("user.dir"), parsedArgs.folder)
C'est le dossier dans lequel java est lancé.
Quant au folder, ce n'est qu'un chemin relatif

https://stackoverflow.com/questions/16239130/java-user-dir-property-what-exactly-does-it-mean

2020-09-07 19:02 UTC, d-fournier commented on library/src/main/kotlin/fr/o80/release/ChangelogGenerator.kt
> +            .takeIf { it.exists() }
Tu veux fail ?

2024-04-25 10:36 UTC, closed without merging